### Get all the countries
GET http://localhost:8080/countries?page=0

### Get country by ID
GET http://localhost:8080/countries/5

### Search countries by prefix
GET http://localhost:8080/countries/search?prefix=fr