### Get all the countries
GET http://localhost:8080/countries?page=2

### Get country by ID
GET http://localhost:8080/countries/10

### Search countries by prefix
GET http://localhost:8080/countries/search?prefix=sp

### Get all country`s names
GET http://localhost:8080/countries/names

### Create new coutry record
POST http://localhost:8080/countries
Content-Type: application/json

{
	"name": "Spain",
	"population": 100000000,
    "cities": [
	  {
        "name": "Madrid"
      },
      {
        "name": "Barcelona"
      }
    ]
}

### Update country record
PUT http://localhost:8080/countries/10
Content-Type: application/json

{
	"name": "Spain",
	"population": 100000000,
	"cities": [
		{
			"name": "Madrid"
		},
		{
			"name": "Barcelona"
		},
        {
          "name": "Valencia"
        }
	]
}

### Delete country record
DELETE http://localhost:8080/countries/10